language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
    - julia -e 'cd(Pkg.dir("MolecularTrajectories")); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

